In [ ]:
import numpy as np


## 01. NumPy
- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리의 근본!

### 1-1 ndarray
- NumPy 의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [ ]:
# ndarray의 생성
a = np.array([[1,2,3], [4,5,6]])
b = np.array([1.0, 3.14, 1.24])

# 배열의 구조
print(f"배열의 구조: {a.shape}")

# 배열의 차원 수
print(f"배열의 차원: {a.ndim}")

# 데이터 타입
print(f"배열의 데이터타입: {a.dtype}")
print(f"배열의 데이터타입: {b.dtype}")

# 형 변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터타입: {new_a.dtype}")

In [ ]:
# 3차원 행렬
a = np.array([[[1,2,3],
                [4,5,6]],

            [[1,2,3],
                [4,5,6]],
                
            [[1,2,3],
                [4,5,6]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

In [ ]:
# 4차원 행렬
a = np.array([[[[1,2,3], 
                    [4,5,6]],
                [[1,2,3], 
                    [4,5,6]],
                [[1,2,3], 
                    [4,5,6]]],
            
            [[[1,2,3],
                [4,5,6]],
            [[1,2,3],
                [4,5,6]],
            [[1,2,3],
                [4,5,6]]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

In [ ]:
# 만들 수 없는 배열
# 내부 배열의 구조가 같아야 함
a = np.array([[1],[2,3]])

### 1-2 배열 초기화

In [ ]:
# 모든 요소가 0인 배열 생성
np.zeros((3, 4)) # 2차원
np.zeros((2, 3, 4), dtype=np.int64) #3차원

In [ ]:
# 모든 요소가 1인 배열 생성
np.ones((5, 6))

In [ ]:
# (원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2, 3))

In [ ]:
# 주어진 값으로 채운 배열
np.full((3,3), 7)

In [ ]:
# 단위 행렬
np.eye(3,3)
np.eye(3,5,1) # 3번째 인자를 입력 → 1이 오른쪽으로 이동, 음수 입력시 반대로 이동

### 1-3 범위 기반 배열 생성

In [ ]:
# arange : range()와 유사한 기능을 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0, 10)
np.arange(0, 10, 2) # 간격 지정

In [ ]:
# linspace : 시작~끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
#  끝을 포함
np.linspace(10, 100, 10) # 10~100 사이 10개로 나눠줘
np.linspace(0, 1, 20) # 0~1 사이 20개로 나눠줘 

In [ ]:
# reshape : 배열의 구조를 재배치
# np.linspace(1,10,10).reshape((2,3)) # error 발생 ➡️ 원소의 개수가 같아야 함
np.linspace(5,100,20).reshape((4,5)) 

### 1-4 랜덤 배열 생성

In [ ]:
# random.rand(m, n) : 0~1 사이의 난수로 초기화
np.random.rand(2, 3)

In [ ]:
# random.randn(m, n) : 표준정규분포를 따르는 난수로 초기화
# 표준정규분포 : 평균 0, 분산 1인 정규분포
np.random.randn(2,4,5)

# random.normal(평균, 분산, 사이즈)
# 정규분포
np.random.normal(10, 20, (2,4))

In [ ]:
# random.randint(low, high, (size))
print(np.random.randint(0, 101, (3, 3)))

In [ ]:
# random.seed() : 난수 생성시 시작값 제공
np.random.seed(42)
print(np.random.rand(2, 3))
print(np.random.randn(2,2))
print(np.random.randint(0, 101, (3, 3)))

In [ ]:
# RNG(Random Number Generator)
# 최근 파이썬 사용에서 권장되는 방식

from numpy.random import default_rng
rng = default_rng(seed=42)
rng2 = default_rng(seed=10)
rng3 = default_rng()

print(rng.random((3,2))) # 0~1 사이의 난수
print(rng2.normal(0, 1, (4,5))) # 정규 분포 난수
print(rng3.integers(0, 100, (2,2))) # 정수 분포 난수
print(rng.uniform(0, 100, (4,4))) # 균등 분포 난수

In [ ]:
# 실습1 문제1. 0으로 채워진 크기 (3, 4) 배열을 생성한 후, 모든 값을 5로 채우는 새로운 배열을 만드세요
a1 = np.zeros((3, 4))
a1_2 = np.full((3,4), 5)
print("문제1:", a1, a1_2, sep="\n")

In [ ]:
# 실습1 문제2 0부터 20까지 2씩 증가하는 1차원 배열을 생성하세요
a2 = np.arange(0, 21, 2)
print("\n문제2:", a2)

In [ ]:
# 실습1 문제3  0~1 사이의 실수 난수를 가지는 (2, 3) 크기의 배열을 생성하세요
a3 = np.random.rand(2, 3)
print("\n문제3:", a3)

In [ ]:
# 실습1 문제4 평균이 100, 표준편차가 20인 정규분포 난수 6개를 생성하세요.
a4 = np.random.normal(100, 20, 6)
print("\n문제4:", a4)

In [ ]:
# 실습1 문제5 1부터 20까지의 정수를 포함하는 1차원 배열을 만들고, 이 배열을 (4, 5) 크기의 2차원 배열로 변환하세요
a5 = np.arange(1, 21).reshape(4, 5)
print("\n문제5:", a5)

In [ ]:
# 실습1 문제6 0부터 1까지 균등 간격으로 나눈 12개의 값을 가지는 배열을 생성하고, 이를 (3, 4) 크기로 변환하세요.
a6 = np.linspace(0, 1, 12).reshape(3, 4)
print("\n문제6:", a6)

In [ ]:
# 실습1 문제7  0~99 사이의 정수 난수로 이루어진 (10, 10) 배열을 생성한 뒤, np.eye()로 만든 단위 행렬을 더하여 대각선 요소가 1씩 증가된 배열을 만드세요.
a7 = np.random.randint(0, 100, (10,10))
a7_eye = np.eye(10,10,1)
a7_added = a7 + np.eye(10,10,1)

print("\n문제7:", a7_added)

In [ ]:
# 실습1 문제8 0~9 사이의 난수로 이루어진 (2, 3, 4) 3차원 배열을 생성하세요
a8 = np.random.randint(0, 10, (2, 3, 4))
print("\n문제8:", a8)
# (2, 3, 4) = 3차원 기준에서 덩어리 2개, 2차원 기준 3개, 1차원 기준 4개

### 1-5. 인덱싱과 슬라이싱
- 다차원 배열을 다루는 편의 기능 제공
- Python의 시퀀스보다 빠름
- NumPy 배열은 Python 시퀀스와 동일하게 0부터 시작하는 인덱스 사용
- 인덱싱과 슬라이싱의 기본적인 문법은 동일함

In [ ]:
# 인덱싱
a = np.array([10, 20, 30, 40, 50])
print(a[2])
print(a[-1])

In [ ]:
# 다차원 인덱싱
# 파이썬 리스트
matrix = [[1,2,3], [4,5,6]]
print("파이썬 인덱싱 방식:", matrix[1][1])

# NumPy 배열
a2 = np.array([[1,2,3], [4,5,6]])
print(a2.shape)
print("NumPy 인덱싱 방식:", a2[1,2])

In [24]:
# 3차원 배열 인덱싱
a3 = np.arange(24).reshape(2, 3, 4)
print(a3)
print(a3.shape)
print("17", a3[1, 1, 1])
print("11", a3[0, 2, 3])
print("23", a3[1, 2, 3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
17 17
11 11
23 23


In [ ]:
# 슬라이싱
# NumPy는 Python 리스트의 슬라이싱과 동일한 문법을 사용
# 결과가 일반 리스트가 아니라 뷰(View)라는 점이 다름
# 뷰(View) - 원본 데이터의 메모리를 공유, 슬라이스 결과를 수정하면 원본 배열도 변경됨
# arr[행_슬라이스, 열__슬라이스]
# arr[..., 4차원슬라이스, 3차원슬라이스, 2차원슬라이스, 1차원슬라이스]
a1 = np.array([10, 20, 30, 40, 50])

print(a1[1:3])
print(a1[2:])
print(a1[:2])
print(a1[:])
print(a1[::2])
print(a1[::-1])

[20 30]
[30 40 50]
[10 20]
[10 20 30 40 50]
[10 30 50]
[50 40 30 20 10]
