In [ ]:
import numpy as np


## 01. NumPy
- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리의 근본!

### 1-1 ndarray
- NumPy 의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [ ]:
# ndarray의 생성
a = np.array([[1,2,3], [4,5,6]])
b = np.array([1.0, 3.14, 1.24])

# 배열의 구조
print(f"배열의 구조: {a.shape}")

# 배열의 차원 수
print(f"배열의 차원: {a.ndim}")

# 데이터 타입
print(f"배열의 데이터타입: {a.dtype}")
print(f"배열의 데이터타입: {b.dtype}")

# 형 변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터타입: {new_a.dtype}")

In [ ]:
# 3차원 행렬
a = np.array([[[1,2,3],
                [4,5,6]],

            [[1,2,3],
                [4,5,6]],
                
            [[1,2,3],
                [4,5,6]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

In [ ]:
# 4차원 행렬
a = np.array([[[[1,2,3], 
                    [4,5,6]],
                [[1,2,3], 
                    [4,5,6]],
                [[1,2,3], 
                    [4,5,6]]],
            
            [[[1,2,3],
                [4,5,6]],
            [[1,2,3],
                [4,5,6]],
            [[1,2,3],
                [4,5,6]]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

In [ ]:
# 만들 수 없는 배열
# 내부 배열의 구조가 같아야 함
a = np.array([[1],[2,3]])

### 1-2 배열 초기화

In [ ]:
# 모든 요소가 0인 배열 생성
np.zeros((3, 4)) # 2차원
np.zeros((2, 3, 4), dtype=np.int64) #3차원

In [ ]:
# 모든 요소가 1인 배열 생성
np.ones((5, 6))

In [ ]:
# (원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2, 3))

In [79]:
# 주어진 값으로 채운 배열
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
# 단위 행렬
np.eye(3,3)
np.eye(3,5,1) # 3번째 인자를 입력 → 1이 오른쪽으로 이동, 음수 입력시 반대로 이동

### 1-3 범위 기반 배열 생성

In [ ]:
# arange : range()와 유사한 기능을 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0, 10)
np.arange(0, 10, 2) # 간격 지정

In [ ]:
# linspace : 시작~끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
#  끝을 포함
np.linspace(10, 100, 10) # 10~100 사이 10개로 나눠줘
np.linspace(0, 1, 20) # 0~1 사이 20개로 나눠줘 

In [89]:
# reshape : 배열의 구조를 재배치
# np.linspace(1,10,10).reshape((2,3)) # error 발생 ➡️ 원소의 개수가 같아야 함
np.linspace(5,100,20).reshape((4,5)) 

array([[  5.,  10.,  15.,  20.,  25.],
       [ 30.,  35.,  40.,  45.,  50.],
       [ 55.,  60.,  65.,  70.,  75.],
       [ 80.,  85.,  90.,  95., 100.]])

### 1-4 랜덤 배열 생성

In [ ]:
# random.rand(m, n) : 0~1 사이의 난수로 초기화
np.random.rand(2, 3)

In [ ]:
# random.randn(m, n) : 표준정규분포를 따르는 난수로 초기화
# 표준정규분포 : 평균 0, 분산 1인 정규분포
np.random.randn(2,4,5)

In [ ]:
# random.randint(low, high, (size))
print(np.random.randint(0, 101, (3, 3)))

In [ ]:
# random.seed() : 난수 생성시 시작값 제공
np.random.seed(42)
print(np.random.rand(2, 3))
print(np.random.randn(2,2))
print(np.random.randint(0, 101, (3, 3)))

In [78]:
# RNG(Random Number Generator)
# 최근 파이썬 사용에서 권장되는 방식

from numpy.random import default_rng
rng = default_rng(seed=42)
rng2 = default_rng(seed=10)
rng3 = default_rng()

print(rng.random((3,2))) # 0~1 사이의 난수
print(rng2.normal(0, 1, (4,5))) # 정규 분포 난수
print(rng3.integers(0, 100, (2,2))) # 정수 분포 난수
print(rng.uniform(0, 100, (4,4))) # 균등 분포 난수

[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]
[[-1.10333845 -0.72502464 -0.78180526  0.26697586 -0.24858073]
 [ 0.12648305  0.84304257  0.85793655  0.47518364 -0.4507686 ]
 [-0.75493228 -0.81481411 -0.34385486 -0.05138009 -0.97227368]
 [-1.13448753  0.30570522 -1.85168503 -0.17705351  0.42582567]]
[[12 35]
 [38 38]]
[[76.1139702  78.60643053 12.81136327 45.03859379]
 [37.07980242 92.67649888 64.38651201 82.27616133]
 [44.34141988 22.72387218 55.4584787   6.38172561]
 [82.7631172  63.16643991 75.80877401 35.45259681]]


In [ ]:
# 실습1 문제1. 0으로 채워진 크기 (3, 4) 배열을 생성한 후, 모든 값을 5로 채우는 새로운 배열을 만드세요
np.zeros((3, 4))
np.full((3,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [82]:
# 실습1 문제2 0부터 20까지 2씩 증가하는 1차원 배열을 생성하세요
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [87]:
# 실습1 문제3  0~1 사이의 실수 난수를 가지는 (2, 3) 크기의 배열을 생성하세요
np.random.rand(2, 3)

array([[0.75536141, 0.42515587, 0.20794166],
       [0.56770033, 0.03131329, 0.84228477]])

In [88]:
# 실습1 문제4 평균이 100, 표준편차가 20인 정규분포 난수 6개를 생성하세요.
np.random.normal(100, 20, 6)

array([ 56.43331506,  79.12207184, 103.45387413, 106.48397535,
       114.91719084,  63.26833521])

In [90]:
# 실습1 문제5 1부터 20까지의 정수를 포함하는 1차원 배열을 만들고, 이 배열을 (4, 5) 크기의 2차원 배열로 변환하세요
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [91]:
# 실습1 문제6 0부터 1까지 균등 간격으로 나눈 12개의 값을 가지는 배열을 생성하고, 이를 (3, 4) 크기로 변환하세요.
np.linspace(0, 1, 12).reshape(3, 4)

array([[0.        , 0.09090909, 0.18181818, 0.27272727],
       [0.36363636, 0.45454545, 0.54545455, 0.63636364],
       [0.72727273, 0.81818182, 0.90909091, 1.        ]])

In [99]:
# 실습1 문제7  0~99 사이의 난수로 이루어진 (10, 10) 배열을 생성한 뒤, np.eye()로 만든 단위 행렬을 더하여 대각선 요소가 1씩 증가된 배열을 만드세요.
a = np.random.randint(0, 100, (10,10))
a + np.eye(10,10,1)

array([[46., 86., 22., 65., 26.,  1., 89., 16., 32.,  8.],
       [42., 47., 39., 92., 41., 25., 98., 49., 24., 23.],
       [12., 59.,  6., 57., 35., 44., 19., 64.,  7., 15.],
       [13., 75., 86., 14., 92., 97., 65., 31., 86., 62.],
       [85., 50., 24., 57., 62., 62., 21., 57., 57., 85.],
       [48., 51., 41., 69., 14., 53., 60., 96.,  7., 52.],
       [59.,  4., 67.,  5., 95., 93., 46., 99., 54., 39.],
       [51., 15., 12., 29., 18., 16., 62., 18., 92., 57.],
       [54., 89., 89., 61., 22.,  8., 11.,  0., 57.,  1.],
       [33., 95., 47., 88.,  0., 15., 60., 63., 62., 68.]])

In [100]:
# 실습1 문제8 0~9 사이의 난수로 이루어진 (2, 3, 4) 3차원 배열을 생성하세요
np.random.randint(0, 10, (2, 3, 4))

array([[[5, 6, 2, 9],
        [2, 4, 5, 8],
        [4, 0, 3, 4]],

       [[9, 9, 4, 6],
        [3, 0, 4, 6],
        [9, 9, 5, 4]]], dtype=int32)