### 2-1. NumPy 배열 연산

In [ ]:
import numpy as np

In [ ]:
# 배열 연산
# NumPy 배열 연산은 요소 단위로 수행됨
# 배열과 배열 간 또는 배열과 스칼라 값 간의 연산을 지원
# 브로드캐스팅을 통해 서로 다른 크기의 배열 간 연산도 자동으로 확장 가능

In [ ]:
# 배열 간 연산(1차원)
# 같은 크기의 배열끼리는 요소별로 연산이 이루어짐
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print((a1 + a2))
print((a1 - a2))

In [ ]:
# 배열 간 연산(2차원)
a1 = np.arange(1, 5).reshape(2,2)
a2 = np.arange(11, 15).reshape(2,2)
print(a1)
print(a2)

print(a1 + a2)
print(a2 - a1)

In [ ]:
# 배열과 스칼라 연산(1차원)
a1 = np.array([1,2,3,4])
print(a1 + 10)
print(a1 * 2)

In [ ]:
# 배열과 스칼라 연산(2차원)
a1 = np.arange(1, 5).reshape(2,2)
a2 = np.arange(11, 15).reshape(2,2)
print(a1)
print(a2)

print(a1 + 5)
print(a2 * 3)
print(a2 / 2)

In [ ]:
# 배열의 구조가 다를 경우
a1 = np.array([1,2])
a2 = np.array([1,2,3])
print(a1 + a2)
# 브로드캐스트 에러 발생 operands could not be broadcast together with shapes (2,) (3,)

In [ ]:
# 브로드캐스팅 
# 자동으로 배열의 크기를 확장 → 서로 다른 크기의 배열 간 연산을 가능하게 하는 기능
# 1. 두 배열의 차원을 뒤(낮은 차원)에서부터 비교
# 2. 크기가 같거나
# 3. 한 쪽이 1인 경우 확장이 가능

a1 = np.array([[1,2,3],[4,5,6]]) # 2x3 배열
a2 = np.array([10,20,30]) # 길이가 3인 1차원 배열

# 1차원 길이3
[10,20,30]

# 2차원으로 변형(1,3)
[[10,20,30]]

# 2차원의 행이 2로 확장
[[10,20,30],[10,20,30]]

print(a1 + a2)

In [ ]:
# 브로드캐스팅 예제
a1 = np.array([[1], [2], [3]]) #(3,1)
a12= np.array([10, 20, 30]) #(3,)

# a2 : (3,) → (1,3)로 변형
[[10, 20, 30]]

# a1과 a2비교 : a1 = (3,1), a2 = (1,3)
# 2차원의 경우 : 3 vs 1 → a2의 2차원이 3으로 확장
[[10,20,30],[10,20,30],[10,20,30]]

# 1차원의 경우 : 1 vs 3 → a1의 1차원이 3으로 확장
[[1,1,1],[2,2,2],[3,3,3]]

# a1
[[1,1,1],[2,2,2],[3,3,3]]
                # +
# a2
[[10,20,30],[10,20,30],[10,20,30]]

print(a1 + a2)

In [22]:
# 브로드캐스팅 불가능한 경우
a1 = np.ones((2,3))
a2 = np.ones((3,2))
a1 + a2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [20]:
# 실습1 문제1 다음 배열을 생성하고, 모든 요소에 3을 더하세요.
arr = np.array([1, 2, 3, 4])
arr2 = np.array([3])
answer = arr + arr2
print(answer)

[4 5 6 7]


In [21]:
# 실습1 문제2 아래 2차원 배열에서 각 요소를 -1로 곱한 새로운 배열을 만드세요.
arr = np.array([[5, 10],
                [15, 20]])
arr2 = np.array([[-1]])
answer = arr * arr2
print(answer)

[[ -5 -10]
 [-15 -20]]


In [15]:
# 실습1 문제3 아래 두 배열의 요소별 곱셈과 나눗셈 결과를 각각 출력하세요.
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])

print("곱셈", arr1 * arr2)
print("나눗셈", arr1 / arr2)


곱셈 [ 2  8 18]
나눗셈 [2. 2. 2.]


In [23]:
# 실습1 문제4 아래 배열에서 모든 요소를 최대값 100으로 만들기 위해 필요한 값을 더한 결과 배열을 브로드캐스팅으로 만드세요.
arr = np.array([[95, 97],
                [80, 85]])
add_values = 100 - arr
print(add_values)
print(arr + add_values)

[[ 5  3]
 [20 15]]
[[100 100]
 [100 100]]


In [17]:
# 실습1 문제5 아래 2차원 배열에서 각 행에 다른 값을 곱하여 새로운 배열을 만드세요.(브로드캐스팅 이용)
arr = np.array([[1,2,3],
                [4,5,6]])
# 첫 번째 행은 10을 곱하고 두 번째 행은 100을 곱해야 합니다.
arr2 = np.array([[10],
                [100]])
answer = arr * arr2
print(answer)

[[ 10  20  30]
 [400 500 600]]


In [18]:
# 실습1 문제6 아래 배열에서 각 행마다 다른 스칼라 값을 더하기 위해 1차원 배열을 만들어 브로드캐스팅 연산을 수행하세요.
# 첫 번째 행에 100, 두 번째 행에 200, 세 번째 행에 300을 더하세요.
arr = np.array([[10, 20],
                [30, 40],
                [50, 60]])
arr2 = np.array([[100],
                [200],
                [300]])
answer = arr + arr2
print(answer)

[[110 120]
 [230 240]
 [350 360]]
