## NumPy(3)

### 3-1 배열의 형태 변형과 차원의 확장/축소

In [ ]:
import numpy as np

In [ ]:
# array.ravel()
# 다차원 배열을 1차원 배열로 펼침
# 결과를 view로 반환(view를 변경시 원본도 변경)
a = np.array([[1,2,3],[4,5,6]])
print(a)

flat = a.ravel()
print(flat)

flat[2] = 100
print(flat)
print(a)

In [ ]:
# array.flatten()
# 다차원 배열을 1차원 배열로 펼침
# 결과를 복사본으로 반환(복사본 변경시 원본은 변경되지 않음)
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

flat = a.flatten()
print(flat)

flat[4] = 0
print(flat)
print(a)

In [ ]:
# np.expand_dims(a, axis)
# 지정한 위치에 차원 추가(차원 확장)
# 추가되는 차원은 1

a = np.array([[1,2,3],[4,5,6]]) # 2 x 3 배열
print("원본", a.shape)

# axis=0 가장 앞쪽에 차원을 추가
a0 = np.expand_dims(a, axis=0)
print("a0", a0.shape)
print("a0", a0)
print()

# axis=1
a1 = np.expand_dims(a, axis=1)
print("a1", a1.shape)
print("a1", a1)
print()

# axis=2
a2 = np.expand_dims(a, axis=2)
print("a2", a2.shape)
print("a2", a2)

In [ ]:
# np.squeeze(a, axis)
# 배열에서 크기가 1인 차원을 제거해주는 함수
a = np.array([[[[1],[2],[3]]], [[[1],[2],[3]]]])
print(a.shape)
s = np.squeeze(a)
print(s)
print(s.shape)

In [ ]:
# axis 지정하는 경우
a2 = np.zeros((1,4,1,2))
print(a2.shape)

s1 = np.squeeze(a2, axis=0)
print(s1.shape)

s2 = np.squeeze(a2, axis=2)
print(s2.shape)

# 차원의 크기가 1이 아닌 차원은 제거할 수 없음
# ValueError: cannot select an axis to squeeze out which has size not equal to one
s3 = np.squeeze(a2, axis=1)

In [ ]:
# np.unique()
# np.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
# 배열에서 중복된 요소를 제거

a = np.array([1,1,1,5,5,2,2,2,2,4,4,4,3,3,3])
u1 = np.unique(a) # 고유값의 오름차순 배열 반환
print(u1)

u2, idx, inv, cnt = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print("인덱스", idx) # 고유값이 원본에서 처음 나타나는 인덱스
print("원본의 고유값 인덱스", inv) # 원본 배열을 재구성할 수 있는 인덱스 배열 반환
print("값의 등장 횟수", cnt) # 각 고유값의 등장 횟수 반환

[1 2 3 4 5]
인덱스 [ 0  5 12  9  3]
원본의 고유값 인덱스 [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
값의 등장 횟수 [3 4 3 3 2]


In [25]:
# 실습1 문제1. 아래의 배열을 사용해서
arr = np.array([[10, 20], [30, 40], [50, 60]])
# 1) ravel과 flatten을 각각 사용해 1차원 배열로 변환하고,
# 2) arr의 첫 번째 원소(arr[0,0])를 999로 바꾼 뒤 ravel 결과와 flatten 결과에 어떤 변화가 있는지 확인하세요.
print(arr.ravel())
print(arr.flatten())
arr[0,0] = 999
print(arr.ravel())
print(arr.flatten())

[10 20 30 40 50 60]
[10 20 30 40 50 60]
[999  20  30  40  50  60]
[999  20  30  40  50  60]


In [26]:
# 실습1 문제2. 크기가 32x32인 이미지 데이터를 가정하고, 이 배열에 대해 expand_dims를 사용하여 shape (1, 32, 32)로 바꾸는 코드를 작성하세요.
img= np.random.rand(32, 32)
print(np.expand_dims(img, axis=0))

[[[0.53066297 0.20611413 0.90750069 ... 0.86544602 0.01825406 0.03846743]
  [0.35140311 0.64004348 0.793041   ... 0.69994422 0.95365681 0.40300264]
  [0.02125194 0.70357277 0.70170006 ... 0.08386402 0.01802491 0.95365088]
  ...
  [0.27721407 0.8965145  0.28574926 ... 0.30486766 0.68645466 0.97204776]
  [0.83937945 0.71324428 0.3343206  ... 0.82357516 0.42304854 0.23128816]
  [0.65995085 0.82869783 0.66131613 ... 0.35666665 0.75975841 0.1596402 ]]]


In [27]:
# 실습1 문제3. 아래 배열에서 불필요한 1차원을 모두 제거하여 shape이 (28, 28)이 되도록 만드세요.
img= np.random.randint(0, 255, (1, 28, 28, 1))
print(np.squeeze(img))

[[116 250 250 127 214 117 206  48 155  21 116   2 151 222 217  41 143  48
  237  59 252 186 197 219   4  63  72 170]
 [170 247 127  10 185  33 233 124 155 191  96 177  80 232 250 170  69 165
    2 231  31 100 110  22 202 200 236 183]
 [237 194 150 220 181 129  61 113 159   0  48 154 199  22  85 104  46 227
   91 145 231 169 175 234 164  23 234  98]
 [192 155  64 108 202  37 189  14  73  93  46 139  29  28  93 145 237 109
  230  18  25  91 188 205 173  95 132 168]
 [229 254 215  91  44 171  29 128  11  10 250 173 137 150 158  85  28 167
  119 126 138   7 103 201 123 250  72 115]
 [106  15  68 136 179 172 176 221  71 244 116 247 183 215 218  61  11  64
    1 135 163 116 175 218 180 143 149  44]
 [105  45 209  71  19  77 161 123 186 254 236 166 200 245 177 103 241  60
  211 131  73 159  50  99 157  27  50 156]
 [111 117  94 106 114 150 225 138 176 203  13  57  53  24 185   7  56 122
  171  43 179 176 152 224 224  11 169  48]
 [  7  23 208 222 227 107  91  49 189  45  80 164  65 239 234 11

In [29]:
# 실습1 문제4. 아래 2차원 배열을 1) 1차원 배열로 만든 후 2) 중복값을 제거한 뒤 shape (1, n)으로 재구성하세요.
arr = np.array([[3, 1, 2, 2],
                [1, 2, 3, 1],
                [2, 2, 1, 4]])
print(np.unique(arr).reshape(1,-1))
a = np.unique(arr).reshape(1,-1)
print(a.shape)


[[1 2 3 4]]
(1, 4)


In [31]:
# 실습1 문제5. 다음 배열을 shape (10,)로 만든 뒤 고유값배열을 구하세요.
arr = np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]])  # shape (1, 10, 1)
flat = arr.flatten()
print(flat)
print(np.unique(flat))

[1 3 2 1 3 2 3 1 2 3]
[1 2 3]


In [36]:
# 실습1 문제6. 다음 배열을 1차원 배열로 만든 후 고유값만 추출해서 shape (고유값 개수, 1)인 2차원 배열로 변환하세요.
arr = np.array([ [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]],
                [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]] ])  # shape (2, 3, 4)
flat = arr.flatten()
print(flat)
uni = np.unique(flat).reshape(-1, 1)
print(uni)
print(uni.shape)

[0 1 2 3 1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7 5 6 7 8]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(9, 1)
